= Restore from Backup

When configuring component-openbao with `backup.enabled = true`, the component sets up regular backups using k8up.
This how-to explains how OpenBao can be restored from such a backup.

== Information on the OpenBao Unseal Key and Root Token

include::partial$openbao-warning.adoc[]

== Prerequisites

* `restic` - command line tool to access backups made by k8up
* `bao` - command line tool to interact with OpenBao
* `kubectl`
* Write access to the cluster's tenant repository
* Read access to the restic repository in which k8up stored the OpenBao backups
* The OpenBao instance's *unseal key* and *root token* - these must be backed up manually; they are not part of the automated k8up backup.

== Procedure

=== 1. Set up new OpenBao instance

. Add the `openbao` application to your cluster configuration.
.. If your old instance of OpenBao is still running on the cluster, you can use component instantiation to create a second instance by adding `openbao as new-openbao` to your application list, and configuring it under `new_openbao`.
. Initially disable backups by setting `.backups.enabled` to `false`
. Compile and push the cluster config and wait for OpenBao to start.

=== 2. Retrieve the OpenBao snapshot

. Set up the restic credentials (values correspond to the component parameters `backup.bucket` and `backup.password`)
+
[source,shell]
----
export AWS_ACCESS_KEY_ID="S3_KEY" # from component configuration: backup.bucket.accesskey
export AWS_SECRET_ACCESS_KEY="S3_SECRET" # from component confiugration: backup.bucket.secretkey
export RESTIC_REPOSITORY="s3:https://path.to.my/bucket"
export RESTIC_PASSWORD="RESTIC_REPO_KEY" # from component configuration: backup.password
----
. Retrieve the latest OpenBao snapshot to your local disk
+
[source,shell]
----
mkdir restore
restic restore --target restore/ latest
----
. Verify the snapshot file
+
[source,shell]
----
ls restore
# This should show a file named "[instance name]-backup.snapshot"
----

=== 3. Restore the snapshot

. Expose the OpenBao pod
+
[source,shell]
----
kubectl port-forward -n $VAULT_INSTANCE_NAME ${VAULT_INSTANCE_NAME}-0 8200
----
. In a separate terminal, prepare the environment to access OpenBao
+
[source,shell]
----
# Get root token to log in
export VAULT_TOKEN="$(kubectl get secret -n $VAULT_INSTANCE_NAME ${VAULT_INSTANCE_NAME}-seal -ojsonpath='{.data.vault-root}' | base64 -d)"
export VAULT_ADDR="http://127.0.0.1:8200"
----
. Restore the backup
+
[source,shell]
----
bao operator raft snapshot restore -force restore/${VAULT_INSTANCE_NAME}-backup.snapshot
----

=== 4. Unseal OpenBao

If you were logged into the OpenBao UI, you should have gotten logged out now.
This is expected.

. Open your browser at http://localhost:8200
. Use the *OpenBao Unseal Key* of the OpenBao instance you've just restored to unseal OpenBao
. Use the *OpenBao root token* of the OpenBao instance you've just restored to log in with the `Token` method
. Verify that the restore worked, and secrets are now restored in OpenBao.

[IMPORTANT]
====
The unseal key and root token of the OpenBao instance you're restoring need to have been stored separately.
Without them, the restore procedure cannot be completed.
====

=== 5. Update the OpenBao Secret

NOTE: Without this step, your OpenBao instance will not be able to auto-unseal.

. Encode the OpenBao credentials
+
[source,shell]
----
export VAULT_UNSEAL_KEY="OLD_UNSEAL_KEY"
export VAULT_ROOT_TOKEN="OLD_ROOT_TOKEN"

echo -n "$VAULT_UNSEAL_KEY" | base64 -w0
echo -n "$VAULT_ROOT_TOKEN" | base64 -w0
----
. Update the OpenBao secret
+
[source,shell]
----
kubectl edit secret -n ${VAULT_INSTANCE_NAME} ${VAULT_INSTANCE_NAME}-seal
----
. Update the `vault-root` and `vault-unseal-0` keys to reflect the values you have just encoded
. Save the secret
. Verify that auto-unseal works:
.. Restart all OpenBao pods simultaneously:
+
[source,shell]
----
kubectl delete pod -n $VAULT_INSTANCE_NAME ${VAULT_INSTANCE_NAME}-{0..2}
----
.. Expose the OpenBao UI
+
[source,shell]
----
kubectl port-forward -n $VAULT_INSTANCE_NAME ${VAULT_INSTANCE_NAME}-0 8200
----
.. Verify that http://localhost:8200[the OpenBao UI] does not prompt you for the unseal key


=== 6. Cleanup

. Reenable `backups.enabled` in the component configuration
